### ISSUE TITLE
Missing support of Cyrillic

### ISSUE THREAD

**Issue by Birdie0** [bbcards/bbcards#3]
Please add support of cyrillic or add Helvetica Neue font

**Comment by arionkrause** [comment]
I finally made it load UTF-8 encoded files by changing line 368:

``` ruby
        lines = IO.readlines(file)
```

to:

``` ruby
        lines = IO.readlines(file, :encoding => "UTF-8")
```

This and using a proper TTF font (Arial, for instance) makes it correctly generate PDF files with special characters.
